import type { Metadata } from 'next'
import '../globals.css'


export const metadata: Metadata = {
  title: 'Darjeeling Limited',
  description: 'Generated by me',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-4xl mx-auto py-10">{children}</body>
    </html>
  )
}
